#!/bin/sh
### Miei alias ###
# Accorciamo i comandi usati spesso
alias p="sudo pacman"
alias lsp="pacman -Qett --color=always | less"
alias SS="sudo systemctl"
alias v="nvim"
alias sv="sudo nvim"
alias ka="killall"
alias mount="sudo mount -v"
alias umount="sudo umount -v"
alias cls="clear"
alias e="emacs -nw" #lancia emacs da terminale
alias se="sudo emacs -nw"
alias f="vifm"
alias g="git"

# Youtube
alias yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'"
alias yta="yt -x -f bestaudio/best"
alias YT="youtube-viewer"

# Anti-cappellamenti
alias ls='ls -hN --color=auto --group-directories-first'
alias ll="ls -al"
alias l="ls -l"
alias mv="mv -iv"
alias cp="cp -iv"
alias rm="rm -v"
alias mkdir="mkdir -v"
alias rmdir="rmdir -v"

# Un po' di colori
alias grep="grep --color=auto"
alias ccat="highlight --out-format=ansi"
alias diff="diff --color=auto"

# Le directory più usate
alias h="cd /home/enrico"
alias vv="cd ~/Video"
alias d="cd ~/Documenti"
alias D="cd ~/Downloads"
#alias D1="cd ~/Download"
alias dl="cd ~/doclatex"
alias wp="cd ~/Immagini/Wallpapers"
alias cfg="cd ~/.config"

# E i file più usati
alias cfv="nvim ~/.vimrc"
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

### Alias di Luke da controllare ###
#	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
#	calcurse="calcurse -D ~/.config/calcurse" \
#	magit="nvim -c Magit" \
#	trem="transmission-remote" \
#	e="$EDITOR" \
#	v="$EDITOR" \
#	x="sxiv -ft *" \
#	sdn="sudo shutdown -h now" \
#	gua="git remote | xargs -L1 git push --all" \
#	ls="ls -hN --color=auto --group-directories-first" \
#	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
#	yta="yt -x -f bestaudio/best" \
#	YT="youtube-viewer" \
#	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
#	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
#	lsp="pacman -Qett --color=always | less" \
#	ffmpeg="ffmpeg -hide_banner"


#shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
#se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
#sv() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
#vf() { fzf | xargs -r -I % $EDITOR % ;}
